# Railway Auto Configuration - Multi Service

[[services]]
name = "backend"
root = "backend"

[services.build]
builder = "NIXPACKS"
buildCommand = "pip install --upgrade pip && pip install -r requirements.txt"

[services.deploy]
startCommand = "gunicorn server:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
healthcheckPath = "/health"

[[services]]
name = "frontend"
root = "frontend"

[services.build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[services.deploy]
startCommand = "npx serve -s build -l $PORT"
healthcheckPath = "/"
