# Railway Auto Configuration - Multi Service

[[services]]
name = "backend"
root = "backend"
buildCommand = "pip install --upgrade pip && pip install -r requirements.txt"
startCommand = "gunicorn server:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
healthcheckPath = "/health"

[[services]]
name = "frontend"
root = "frontend"
buildCommand = "npm ci && npm run build"
startCommand = "npx serve -s build -l $PORT"
healthcheckPath = "/"
