[build]
builder = "NIXPACKS"
buildCommand = "cd backend && pip install -r requirements.txt && cd ../frontend && npm install && npm run build"

[deploy]
startCommand = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.environmentVariables]]
name = "SUPABASE_URL"
description = "Supabase Project URL"

[[deploy.environmentVariables]]
name = "SUPABASE_KEY"
description = "Supabase Service Role Key"

[[deploy.environmentVariables]]
name = "JWT_SECRET_KEY"
description = "JWT Secret for Authentication"
default = "change-this-super-secret-key-in-production-123456789"

[[deploy.environmentVariables]]
name = "STRIPE_SECRET_KEY"
description = "Stripe Secret Key for Payments"

[[deploy.environmentVariables]]
name = "STRIPE_PUBLISHABLE_KEY"
description = "Stripe Publishable Key"

[[deploy.environmentVariables]]
name = "STRIPE_WEBHOOK_SECRET"
description = "Stripe Webhook Secret"

[[deploy.environmentVariables]]
name = "FRONTEND_URL"
description = "Frontend URL for CORS"
default = "https://shareyoursales.ma"

[[deploy.environmentVariables]]
name = "BACKEND_URL"
description = "Backend API URL"

[[deploy.environmentVariables]]
name = "ENVIRONMENT"
description = "Environment (development, staging, production)"
default = "production"

[[deploy.environmentVariables]]
name = "DATABASE_URL"
description = "Supabase Database Connection String"

[[deploy.environmentVariables]]
name = "REDIS_URL"
description = "Redis URL for Caching (optional)"
default = ""

[[deploy.environmentVariables]]
name = "SENTRY_DSN"
description = "Sentry DSN for Error Tracking (optional)"
default = ""

[[deploy.environmentVariables]]
name = "EMAIL_HOST"
description = "SMTP Host for Emails"
default = "smtp.gmail.com"

[[deploy.environmentVariables]]
name = "EMAIL_PORT"
description = "SMTP Port"
default = "587"

[[deploy.environmentVariables]]
name = "EMAIL_USERNAME"
description = "SMTP Username"

[[deploy.environmentVariables]]
name = "EMAIL_PASSWORD"
description = "SMTP Password"

[[deploy.environmentVariables]]
name = "EMAIL_FROM"
description = "From Email Address"
default = "contact@shareyoursales.ma"
